NodeRewardWebhookDelay = 10.0

[Features]
  # Feature heights for testnet.  See docker-config-default.toml for more information.
  NoExchangeHoldsOnTransfer = 13_510
  NoKeysOnSetValidation = 13_510
  ResetUncreditedEAIOnCreditEAI = 13_510
  # Repaved testnet with snapshot-mainnet-30418.  Turn on new features after that.
  NodeActiveCheck = 30_419
  NoLeakyUpdateState = 30_419
  SequenceIncrementProtection = 30_419
  CreditEAIUnlocksAccounts = 30_419
  ApplyUncreditedEAI = 30_419
  FixEAIUnlockBug = 30_419
  TargetPrice9999 = 30_419
  SysvarValidityCheck = 30_419
