[[constraint]]
name = "github.com/oneiro-ndev/metanode"
version = "~v0.11"

[[constraint]]
name = "github.com/oneiro-ndev/chaos"
branch = "prgn-validate-with-sidechaintx"

[[constraint]]
name = "github.com/oneiro-ndev/ndau"
branch = "prgn-sidechaintx"

[[constraint]]
name = "github.com/oneiro-ndev/chaos_genesis"
version = "~v0.1"

[[constraint]]
name = "github.com/oneiro-ndev/genesis"
branch = "master"
