[[constraint]]
name = "github.com/oneiro-ndev/chaincode"
version = "~v0.21"

[[constraint]]
name = "github.com/oneiro-ndev/chaos"
version = "~v0.14"

[[constraint]]
name = "github.com/oneiro-ndev/chaos_genesis"
version = "~v0.1"

[[constraint]]
name = "github.com/oneiro-ndev/genesis"
# branch = "master"
branch = "prgn-fix-row-number-leak"

[[constraint]]
name = "github.com/oneiro-ndev/json2msgp"
branch = "master"

[[constraint]]
name = "github.com/oneiro-ndev/metanode"
version = "~v0.12"

[[constraint]]
name = "github.com/oneiro-ndev/ndau"
# version = "~v0.17"
branch = "prgn-delegates-query"

[[constraint]]
name = "github.com/oneiro-ndev/ndaumath"
version = "~v0.11"

[[constraint]]
name = "github.com/oneiro-ndev/o11y"
version = "~v1.3"

[[constraint]]
name = "github.com/oneiro-ndev/system_vars"
version = "~v0.2"

[[override]]
name = "github.com/attic-labs/graphql"
branch = "master"

[[override]]
name = "github.com/tinylabs/msgp"
version = "v1.1.0"

[[override]]
name = "github.com/attic-labs/noms"
branch = "master"
source = "github.com/oneiro-ndev/noms"

[[override]]
name = "github.com/tendermint/tendermint"
version = "v0.30.0"

[[override]]
name = "github.com/gofrs/uuid"
version = "~v3.2"
