[[constraint]]
name = "github.com/oneiro-ndev/chaincode"
version = "~v1.2"

[[constraint]]
name = "github.com/oneiro-ndev/genesis"
version = "~v1.2"

[[constraint]]
name = "github.com/oneiro-ndev/json2msgp"
version = "~v1.1"

[[constraint]]
name = "github.com/oneiro-ndev/metanode"
version = "~v1.8"

[[constraint]]
name = "github.com/oneiro-ndev/ndau"
branch = "eas-commands-396.1"
#version = "~v1.24"

[[constraint]]
name = "github.com/oneiro-ndev/ndaumath"
version = "~v1.3"

[[constraint]]
name = "github.com/oneiro-ndev/o11y"
version = "~v1.3"

[[constraint]]
name = "github.com/oneiro-ndev/rest"
version = "~v0.1"

[[constraint]]
name = "github.com/oneiro-ndev/system_vars"
version = "~v1.5"

[[constraint]]
name = "github.com/oneiro-ndev/writers"
version = "~v1.1"

[[constraint]]
name = "github.com/alexflint/go-arg"
version = "v1.1"

[[override]]
name = "github.com/attic-labs/graphql"
branch = "master"

[[override]]
name = "github.com/attic-labs/noms"
branch = "master"

[[override]]
name = "github.com/gofrs/uuid"
version = "~v3.2"

[[override]]
name = "github.com/tendermint/tendermint"
version = "=v0.32.3"

[[override]]
name = "github.com/tinylabs/msgp"
version = "v1.1.0"

[[override]]
# why do we do this meaningless thing, given that golang/x/* packages
# are specified by the go compiler? In short, Tendermint made some bad
# versioning choices, and this helps fix them.
# https://ndevtalk.slack.com/archives/CFT5J0N81/p1551689341081100
name = "golang.org/x/crypto"

