[[constraint]]
name = "github.com/oneiro-ndev/chaos"
version = "~v0.11"

[[constraint]]
name = "github.com/oneiro-ndev/chaos_genesis"
version = "~v0.1"

[[constraint]]
name = "github.com/oneiro-ndev/genesis"
branch = "master"

[[constraint]]
name = "github.com/oneiro-ndev/metanode"
version = "~v0.11"

[[constraint]]
name = "github.com/oneiro-ndev/ndau"
version = "~v0.8"

[[override]]
name = "github.com/attic-labs/graphql"
branch = "master"

[[override]]
name = "github.com/attic-labs/noms"
branch = "master"
source = "github.com/oneiro-ndev/noms"

[[override]]
name = "github.com/satori/go.uuid"
branch = "master"

[[override]]
name = "github.com/oneiro-ndev/writers"
branch = "master"
