[[constraint]]
name = "github.com/oneiro-ndev/chaincode"
# version = "~v1.1"
branch = "prgn-crank"

[[constraint]]
name = "github.com/oneiro-ndev/genesis"
version = "~v1.1"

[[constraint]]
name = "github.com/oneiro-ndev/json2msgp"
version = "~v1.0"

[[constraint]]
name = "github.com/oneiro-ndev/metanode"
version = "~v1.4"

[[constraint]]
name = "github.com/oneiro-ndev/ndau"
version = "~v1.18"

[[constraint]]
name = "github.com/oneiro-ndev/ndaumath"
version = "~v1.3"

[[constraint]]
name = "github.com/oneiro-ndev/o11y"
version = "~v1.3"

[[constraint]]
name = "github.com/oneiro-ndev/system_vars"
version = "~v1.2"

[[override]]
name = "github.com/attic-labs/graphql"
branch = "master"

[[override]]
name = "github.com/attic-labs/noms"
branch = "master"
source = "github.com/oneiro-ndev/noms"

[[override]]
name = "github.com/gofrs/uuid"
version = "~v3.2"

[[override]]
name = "github.com/tendermint/tendermint"
version = "v0.31.4"

[[override]]
name = "github.com/tinylabs/msgp"
version = "v1.1.0"

[[override]]
# why do we do this meaningless thing, given that golang/x/* packages
# are specified by the go compiler? In short, Tendermint made some bad
# versioning choices, and this helps fix them.
# https://ndevtalk.slack.com/archives/CFT5J0N81/p1551689341081100
name = "golang.org/x/crypto"

