[env]
NDAU_DIR = "../ndau"
NOMS_DIR = "../../attic-labs/noms"
TENDERMINT_DIR = "../../tendermint/tendermint"

LOCALNET = "$HOME/.localnet/data"

NODE_DATA_DIR = "$LOCALNET/ndau"
NOMS_DATA_DIR = "$LOCALNET/noms-ndau"
REDIS_DATA_DIR = "$LOCALNET/redis-ndau"
TENDERMINT_DATA_DIR = "$LOCALNET/tendermint-ndau"
LOGDIR = "bin"
NODE_NUM = "0"
FORMAT = "text"
LOGLEVEL = "info"
REDIS_PORT_NUM = "6379"
NOMS_PORT_NUM = "8000"
NODE_PORT_NUM = "26650"
TM_DATA_DIR = "data"
TM_P2P_PORT_NUM = "26660"
TM_RPC_PORT_NUM = "26670"
NDAUAPI_PORT = "3030"
NDAUAPI_NDAU_RPC_URL="http://localhost:$TM_RPC_PORT_NUM"
NDAUHOME = "$NODE_DATA_DIR-$NODE_NUM"
MONIKER_PREFIX = "localnet"
NODE_ID = "$MONIKER_PREFIX-$NODE_NUM"

[logger]
output = "STDERR"
format = "$FORMAT"
level = "$LOGLEVEL"

[[prologue]]
    name = "redisportclear"
    type = "portavailable"
    port = "$REDIS_PORT_NUM"

[[prologue]]
    name = "nomsportclear"
    type = "portavailable"
    port = "$NOMS_PORT_NUM"

[[prologue]]
    name = "nodeportclear"
    type = "portavailable"
    port = "$NODE_PORT_NUM"

[[prologue]]
    name = "tmportsclear"
    type = "portavailable"
    port = "$TM_P2P_PORT_NUM $TM_RPC_PORT_NUM"

[[prologue]]
    name = "ndauapiportclear"
    type = "portavailable"
    port = "$NDAUAPI_PORT"

[[prologue]]
    name = "node datadir exists"
    type = "ensuredir"
    path = "$NODE_DATA_DIR"

[[prologue]]
    name = "noms datadir exists"
    type = "ensuredir"
    path = "$NOMS_DATA_DIR"

[[prologue]]
    name = "redis datadir exists"
    type = "ensuredir"
    path = "$REDIS_DATA_DIR"

[[prologue]]
    name = "tm datadir exists"
    type = "ensuredir"
    path = "$TENDERMINT_DATA_DIR"


# environment variables are expanded in all config values that are
# strings
[[task]]
    name = "redis"
    path = "redis-server"
    args = [
        "--dir", "$REDIS_DATA_DIR-$NODE_NUM",
        "--port", "$REDIS_PORT_NUM",
        "--save", "60", "1",
    ]
    # special values are:
    # "SUPPRESS" (also "") meaning "discard this stream"
    # stderr = "STDOUT" means "send stderr also to stdout's destination"
    # "HONEYCOMB" sends the message to honeycomb
    # Anything else is a named file
    stdout = "$LOGDIR/redis-$NODE_NUM.log"
    stderr = "$LOGDIR/redis-$NODE_NUM.log"
    # durations are done as time.Duration
    maxshutdown = "5s"

    [[task.monitors]]
        name = "health"
        type = "redis"
        addr = "localhost:$REDIS_PORT_NUM"
        period = "2s"

    [[task.monitors]]
        name = "ready"
        type = "redis"
        addr = "localhost:$REDIS_PORT_NUM"


[[task]]
    name = "noms"
    parent = "redis"
    path = "$NOMS_DIR/noms"
    args = [
        "serve",
        "--port=$NOMS_PORT_NUM",
        "$NOMS_DATA_DIR-$NODE_NUM",
    ]
    stdout = "$LOGDIR/noms-$NODE_NUM.log"
    stderr = "$LOGDIR/noms-$NODE_NUM.log"
    maxshutdown = "5s"

    [[task.monitors]]
        name = "health"
        type = "portinuse"
        port = "$NOMS_PORT_NUM"
        period = "2s"

    [[task.monitors]]
        name = "ready"
        type = "portinuse"
        port = "$NOMS_PORT_NUM"

[[task]]
    name = "ndaunode"
    parent = "noms"
    path = "./ndaunode"
    # prerun = [ "ndau_apphash" ]
    args = [
        "-spec", "http://localhost:$NOMS_PORT_NUM",
        "-index", "localhost:$REDIS_PORT_NUM",
        "-addr", "0.0.0.0:$NODE_PORT_NUM",
    ]
    stdout = "$LOGDIR/ndaunode-$NODE_NUM.log"
    stderr = "$LOGDIR/ndaunode-$NODE_NUM.log"
    maxstartup = "5s"
    maxshutdown = "5s"

    [[task.monitors]]
        name = "health"
        type = "portinuse"
        port = "$NODE_PORT_NUM"
        period = "2s"

    [[task.monitors]]
        name = "ready"
        type = "portinuse"
        port = "$NODE_PORT_NUM"

[[task]]
    name = "ndau_tm"
    parent = "ndaunode"
    path = "$TENDERMINT_DIR/tendermint"
    args = [
        "node",
        "--home", "$TENDERMINT_DATA_DIR-$NODE_NUM",
        "--proxy_app", "tcp://localhost:$NODE_PORT_NUM",
        "--p2p.laddr", "tcp://0.0.0.0:$TM_P2P_PORT_NUM",
        "--rpc.laddr", "tcp://0.0.0.0:$TM_RPC_PORT_NUM",
        "--log_level=*:$LOGLEVEL",
    ]
    stdout = "$LOGDIR/ndau_tm-$NODE_NUM.log"
    stderr = "$LOGDIR/ndau_tm-$NODE_NUM.log"
    maxshutdown = "5s"

    [[task.monitors]]
        name = "health"
        type = "portinuse"
        port = "$TM_P2P_PORT_NUM"
        period = "2s"

    [[task.monitors]]
        name = "health"
        type = "portinuse"
        port = "$TM_RPC_PORT_NUM"
        period = "2s"

    [[task.monitors]]
        name = "ready"
        type = "portinuse"
        port = "$TM_P2P_PORT_NUM $TM_RPC_PORT_NUM"

[[task]]
    name = "ndau_api"
    parent = "ndau_tm"
    path = "./ndauapi"
    args = []
    stdout = "$LOGDIR/ndauapi-$NODE_NUM.log"
    stderr = "$LOGDIR/ndauapi-$NODE_NUM.log"
    maxstartup  = "5s"
    maxshutdown = "2s"

    [[task.monitors]]
        name = "health"
        type = "http"
        url = "http://localhost:$NDAUAPI_PORT/node/health"
        timeout = "1s"
        period =  "2s"

    [[task.monitors]]
        name = "ready"
        type = "http"
        url = "http://localhost:$NDAUAPI_PORT/node/health"
        timeout = "300ms"
