version: 2.1

commands:
  setup:
    description: "Set up things"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "7d:f1:8e:9e:99:9a:26:e2:4d:0c:66:f3:d4:74:10:e7"
      - setup_remote_docker:
          docker_layer_caching: false

      - run:
          name: Turn environment variable secrets into files
          command: |
            # install helm certs
            mkdir -p /root/.helm
            echo -e "$helm_ca_pem" > /root/.helm/ca.pem
            echo -e "$helm_cert_pem" > /root/.helm/cert.pem
            echo -e "$helm_key_pem" > /root/.helm/key.pem

            # install kube config certs
            echo -e "$kube_config" > /root/kubeconfig

            # AWS ECR Login
            eval $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})

      - run:
          name: Checkout code
          command: |
            # depth=1 makes the clone a lot faster
            git clone $CIRCLE_REPOSITORY_URL -b $CIRCLE_BRANCH /commands --depth=1

            # add the circle image's known_hosts file to the known_hosts used inside the images
            cp /root/.ssh/known_hosts /commands/deploy/known_hosts

            # install github machine user key
            # This needs to be here. Otherwise git will cowardly refuse to clone into an non-empty directory.
            echo -e "$machine_user_key" > /commands/machine_user_key
      - run:
          name: get git information
          command: |
            cd /commands
            echo "export VERSION=$(git describe --long --tags)" >> $BASH_ENV
            echo "export SHA=$(git rev-parse --short $CIRCLE_SHA1)" >> $BASH_ENV

workflows:
  version: 2
  deps-test-push-deploy:
    jobs:
      - deps:
          filters:  # required since `test` has tag filters AND requires `deps`
            tags:
              only: /.*/
      - test:
          requires:
            - deps
          filters:  # required since `push` has tag filters AND requires `test`
            tags:
              only: /.*/
      - push:
          requires:
            - test
          filters:  # required since `deploy` has tag filters AND requires `push`
            tags:
              only: /.*push|deploy.*/
      - deploy:
          requires:
            - push
          filters:
            tags:
              only: /.*deploy.*/
            branches:
              ignore: /.*/
      - int:
          requires:
            - deploy
          filters:
            tags:
              only: /.*deploy.*/
            branches:
              ignore: /.*/

jobs:
  deps:
    working_directory: /commands
    docker:
      - image: 578681496768.dkr.ecr.us-east-1.amazonaws.com/circle-ci:0.0.9
    environment:
      shell: /bin/bash
      # Used for ECR
      AWS_DEFAULT_REGION: us-east-1
      # ECR's
      ECR_ENDPOINT: 578681496768.dkr.ecr.us-east-1.amazonaws.com
      # Bump these versions, and commit to master to upload a new version to ECR
      NOMS_CONTAINER_VERSION: 0.0.1
      STARTING_PORT: "30050"
      ELB_SUBDOMAIN: api.ndau.tech # nodes will be accessible from mario.api.ndau.tech
      # These node names are removed first before new ones are installed.
      # If these names change, the old names will have to be removed manually.
      NODE_NAMES: "devnet-0 devnet-1 devnet-2 devnet-3 devnet-4"
      RELEASE_NAME: "devnet"
      # Number of nodes to deploy
      NODE_NUM: "5"
      KUBECONFIG: /root/kubeconfig

    steps:
      - setup
      - run:
          name: build the deps image
          command: docker build -t deps -f /commands/deploy/deps.docker /commands/

  test:
    working_directory: /commands
    docker:
      - image: 578681496768.dkr.ecr.us-east-1.amazonaws.com/circle-ci:0.0.9
    environment:
      shell: /bin/bash
      # Used for ECR
      AWS_DEFAULT_REGION: us-east-1
      # ECR's
      ECR_ENDPOINT: 578681496768.dkr.ecr.us-east-1.amazonaws.com
      # Bump these versions, and commit to master to upload a new version to ECR
      NOMS_CONTAINER_VERSION: 0.0.1
      STARTING_PORT: "30050"
      ELB_SUBDOMAIN: api.ndau.tech # nodes will be accessible from mario.api.ndau.tech
      # These node names are removed first before new ones are installed.
      # If these names change, the old names will have to be removed manually.
      NODE_NAMES: "devnet-0 devnet-1 devnet-2 devnet-3 devnet-4"
      RELEASE_NAME: "devnet"
      # Number of nodes to deploy
      NODE_NUM: "5"
      KUBECONFIG: /root/kubeconfig

    steps:
      - setup
      - run:
          name: Run tests
          command: |
            # this runs a test script within the deps image
            docker run --rm \
                -e CI=true \
                deps \
                /bin/sh /root/tests.sh

  push:
    working_directory: /commands
    docker:
      - image: 578681496768.dkr.ecr.us-east-1.amazonaws.com/circle-ci:0.0.9
    environment:
      shell: /bin/bash
      # Used for ECR
      AWS_DEFAULT_REGION: us-east-1
      # ECR's
      ECR_ENDPOINT: 578681496768.dkr.ecr.us-east-1.amazonaws.com
      # Bump these versions, and commit to master to upload a new version to ECR
      NOMS_CONTAINER_VERSION: 0.0.1
      STARTING_PORT: "30050"
      ELB_SUBDOMAIN: api.ndau.tech # nodes will be accessible from mario.api.ndau.tech
      # These node names are removed first before new ones are installed.
      # If these names change, the old names will have to be removed manually.
      NODE_NAMES: "devnet-0 devnet-1 devnet-2 devnet-3 devnet-4"
      RELEASE_NAME: "devnet"
      # Number of nodes to deploy
      NODE_NUM: "5"
      KUBECONFIG: /root/kubeconfig

    steps:
      - setup
      - run:
          name: run all sub project docker scripts
          command: find . -name "docker-build-push.sh" -exec {} \;

  deploy:
    working_directory: /commands
    docker:
      - image: 578681496768.dkr.ecr.us-east-1.amazonaws.com/circle-ci:0.0.9
    environment:
      shell: /bin/bash
      # Used for ECR
      AWS_DEFAULT_REGION: us-east-1
      # ECR's
      ECR_ENDPOINT: 578681496768.dkr.ecr.us-east-1.amazonaws.com
      # Bump these versions, and commit to master to upload a new version to ECR
      NOMS_CONTAINER_VERSION: 0.0.1
      STARTING_PORT: "30050"
      ELB_SUBDOMAIN: api.ndau.tech # nodes will be accessible from mario.api.ndau.tech
      # These node names are removed first before new ones are installed.
      # If these names change, the old names will have to be removed manually.
      NODE_NAMES: "devnet-0 devnet-1 devnet-2 devnet-3 devnet-4"
      RELEASE_NAME: "devnet"
      # Number of nodes to deploy
      NODE_NUM: "5"
      KUBECONFIG: /root/kubeconfig

    steps:
      - setup
      - run:
          name: run the deploy script
          command: |

            # Redeploy nodegroup testnet

            # Clone the automation repo master branch
            git clone git@github.com:oneiro-ndev/automation.git /root/automation

            # Remove old test net
            helm del --purge $NODE_NAMES --tls ||\
                echo "Releases: $NODE_NAMES could not be deleted" >&2

            # create new multinode test net
            # Use $SHA here instead of the automation's git ls-remote method.
            CHAOSNODE_TAG=$SHA \
            NDAUNODE_TAG=$SHA \
            RELEASE=$RELEASE_NAME \
            ELB_SUBDOMAIN=$ELB_SUBDOMAIN \
                /root/automation/testnet/gen_node_groups.py $NODE_NUM $STARTING_PORT

  integration:
    working_directory: /commands
    docker:
      - image: 578681496768.dkr.ecr.us-east-1.amazonaws.com/circle-ci:0.0.9
    environment:
      shell: /bin/bash
      # Used for ECR
      AWS_DEFAULT_REGION: us-east-1
      # ECR's
      ECR_ENDPOINT: 578681496768.dkr.ecr.us-east-1.amazonaws.com
      # Bump these versions, and commit to master to upload a new version to ECR
      NOMS_CONTAINER_VERSION: 0.0.1
      STARTING_PORT: "30050"
      ELB_SUBDOMAIN: api.ndau.tech # nodes will be accessible from mario.api.ndau.tech
      # These node names are removed first before new ones are installed.
      # If these names change, the old names will have to be removed manually.
      NODE_NAMES: "devnet-0 devnet-1 devnet-2 devnet-3 devnet-4"
      RELEASE_NAME: "devnet"
      # Number of nodes to deploy
      NODE_NUM: "5"
      KUBECONFIG: /root/kubeconfig

    steps:
      - setup
      - run:
          name: Integration tests
          command: |

            # Run integration tests
            # get address and port of devnet0 RPC
            NODE_IP_ADDRESS=$(kubectl get nodes -o jsonpath='{.items[*].status.addresses[?(@.type=="ExternalIP")].address}' | cut -d " " -f1)
            NODE_PORT_0=$(kubectl get service --namespace default -o jsonpath='{.spec.ports[?(@.name=="rpc")].nodePort}' devnet-0-nodegroup-ndau-tendermint-service)
            # get address and port of devnet1 RPC
            NODE_PORT_1=$(kubectl get service --namespace default -o jsonpath='{.spec.ports[?(@.name=="rpc")].nodePort}' devnet-1-nodegroup-ndau-tendermint-service)

            URL_0=http://$NODE_IP_ADDRESS:$NODE_PORT_0/node/status
            URL_1=http://$NODE_IP_ADDRESS:$NODE_PORT_1/node/status

            # curl retry options
            CURL_CONNECT_TIMEOUT=5  # each try waits X seconds
            CURL_RETRY_MAX=50       # retry X many times
            CURL_RETRY_TOTAL=1000   # arbitrary high number, it will timeout first.
            CURL_RETRY_DELAY=10     # try every X seconds
            CURL_TOTAL_TIMEOUT=900  # total seconds before it fails (900s=15m)

            echo "Trying to connect to $URL_0"
            # curl until devnet-0 RPC is up and running, or CURL_TOTAL_TIMEOUT passes
            if curl --connect-timeout $CURL_CONNECT_TIMEOUT \
                --retry-connrefused \
                --max-time $CURL_RETRY_MAX \
                --retry $CURL_RETRY_TOTAL \
                --retry-delay $CURL_RETRY_DELAY \
                --retry-max-time $CURL_TOTAL_TIMEOUT \
                $URL_0; then
                echo "Pinged $URL_0"
            else
                echo "Can't ping $URL_0"
                exit 1
            fi

            echo "Trying to connect to $URL_1"
            # curl until devnet-1 RPC is up and running, or CURL_TOTAL_TIMEOUT passes
            if curl --connect-timeout $CURL_CONNECT_TIMEOUT \
                --retry-connrefused \
                --max-time $CURL_RETRY_MAX \
                --retry $CURL_RETRY_TOTAL \
                --retry-delay $CURL_RETRY_DELAY \
                --retry-max-time $CURL_TOTAL_TIMEOUT \
                $URL_1; then
                echo "Pinged $URL_1"
            else
                echo "Can't ping $URL_1"
                exit 1
            fi

            # ensure go path location
            mkdir -p /go/src/github.com/oneiro-ndev
            cd /go/src/github.com/oneiro-ndev

            # clone integration tests
            git clone git@github.com:oneiro-ndev/integration-tests.git
            cd integration-tests

            # run tests
            pipenv sync
            pipenv run pytest -v --run_kub

