["A2etqqaA3qQExilg+ywQ4ElRsyoDJh9lR5A+Thg5PcTR"]
  ["A2etqqaA3qQExilg+ywQ4ElRsyoDJh9lR5A+Thg5PcTR".Q29tbWFuZFZhbGlkYXRvckNoYW5nZUFkZHJlc3M]
    comment = "CommandValidatorChangeAddress"
    go_type = "address.Address"
    data = "ndnf9ffbzhyf8mk7z5vvqc4quzz5i2exp5zgsmhyhc9cuwr4"
    system = true
  ["A2etqqaA3qQExilg+ywQ4ElRsyoDJh9lR5A+Thg5PcTR".RGVmYXVsdFNldHRsZW1lbnREdXJhdGlvbg]
    comment = "DefaultSettlementDuration"
    go_type = "math.Duration"
    data = "2d"
    system = true
  ["A2etqqaA3qQExilg+ywQ4ElRsyoDJh9lR5A+Thg5PcTR".RUFJRmVlVGFibGU]
    comment = "EAIFeeTable"
    go_type = "[]sv.EAIFee"
    data = ["4000000:ndaea8w9gz84ncxrytepzxgkg9ymi4k7c9p427i6b57xw3r4", "1000000:ndmmw2cwhhgcgk9edp5tiieqab3pq7uxdic2wabzx49twwxh", "100000:ndakj49v6nnbdq3yhnf8f2j6ivfzicedvfwtunckivfsw9qt", "100000:ndnf9ffbzhyf8mk7z5vvqc4quzz5i2exp5zgsmhyhc9cuwr4", "9800000:"]
    system = true
  ["A2etqqaA3qQExilg+ywQ4ElRsyoDJh9lR5A+Thg5PcTR".TG9ja2VkUmF0ZVRhYmxl]
    comment = "LockedRateTable"
    go_type = "[]eai.RTRow"
    data = ["3m:1%", "6m:2%", "1y:3%", "2y:4%", "3y:5%"]
    system = true
  ["A2etqqaA3qQExilg+ywQ4ElRsyoDJh9lR5A+Thg5PcTR".TWluRHVyYXRpb25CZXR3ZWVuTm9kZVJld2FyZE5vbWluYXRpb25z]
    comment = "MinDurationBetweenNodeRewardNominations"
    go_type = "math.Duration"
    data = "1d"
    system = true
  ["A2etqqaA3qQExilg+ywQ4ElRsyoDJh9lR5A+Thg5PcTR".TWluTm9kZVJlZ2lzdHJhdGlvblN0YWtlQW1vdW50]
    comment = "MinNodeRegistrationStakeAmount"
    go_type = "math.Ndau"
    data = 100000000000
    system = true
  ["A2etqqaA3qQExilg+ywQ4ElRsyoDJh9lR5A+Thg5PcTR".Tm9kZUdvb2RuZXNzRnVuY3Rpb24]
    comment = "NodeGoodnessFunction"
    go_type = "[]uint8"
    data = "oACI"
    system = true
  ["A2etqqaA3qQExilg+ywQ4ElRsyoDJh9lR5A+Thg5PcTR".Tm9kZVJld2FyZE5vbWluYXRpb25UaW1lb3V0]
    comment = "NodeRewardNominationTimeout"
    go_type = "math.Duration"
    data = "t30s"
    system = true
  ["A2etqqaA3qQExilg+ywQ4ElRsyoDJh9lR5A+Thg5PcTR".Tm9taW5hdGVOb2RlUmV3YXJkQWRkcmVzcw]
    comment = "NominateNodeRewardAddress"
    go_type = "address.Address"
    data = "ndnf9ffbzhyf8mk7z5vvqc4quzz5i2exp5zgsmhyhc9cuwr4"
    system = true
  ["A2etqqaA3qQExilg+ywQ4ElRsyoDJh9lR5A+Thg5PcTR".UmVsZWFzZUZyb21FbmRvd21lbnRBZGRyZXNz]
    comment = "ReleaseFromEndowmentAddress"
    go_type = "address.Address"
    data = "ndmfgnz9qby6nyi35aadjt9nasjqxqyd4vrswucwfmceqs3y"
    system = true
  ["A2etqqaA3qQExilg+ywQ4ElRsyoDJh9lR5A+Thg5PcTR".VHJhbnNhY3Rpb25GZWVTY3JpcHQ]
    comment = "TransactionFeeScript"
    go_type = "[]uint8"
    data = "oAAgiA=="
    system = true
  ["A2etqqaA3qQExilg+ywQ4ElRsyoDJh9lR5A+Thg5PcTR".VW5sb2NrZWRSYXRlVGFibGU]
    comment = "UnlockedRateTable"
    go_type = "[]eai.RTRow"
    data = ["1m:2%", "2m:3%", "3m:4%", "4m:5%", "5m:6%", "6m:7%", "7m:8%", "8m:9%", "9m:10%"]
    system = true
  ["A2etqqaA3qQExilg+ywQ4ElRsyoDJh9lR5A+Thg5PcTR".c3Zp]
    comment = "svi"
    go_type = "string"
    data = "SVI stub: will be automatically filled in"
    svi_stub = true
