NodeRewardWebhookDelay = 10.0

[Features]
  # Feature heights for testnet.  See docker-config-default.toml for more information.
  NoExchangeHoldsOnTransfer = 13_510
  NoKeysOnSetValidation = 13_510
  ResetUncreditedEAIOnCreditEAI = 13_510
  NodeActiveCheck = 25_000
  NoLeakyUpdateState = 25_000
  SequenceIncrementProtection = 25_000
  CreditEAIUnlocksAccounts = 25_000
  ApplyUncreditedEAI = 25_000
  FixEAIUnlockBug = 25_000
  TargetPrice9999 = 25_000
