NodeRewardWebhookDelay = 10.0

[Features]
  # Feature heights for mainnet.  See docker-config-default.toml for more information.
  NoExchangeHoldsOnTransfer = 13_510
  NoKeysOnSetValidation = 13_510
  ResetUncreditedEAIOnCreditEAI = 13_510
  # TODO: Adjust the following heights when upgrading mainnet next, then remove this comment.
  NodeActiveCheck = 99_000
  NoLeakyUpdateState = 99_000
  SequenceIncrementProtection = 99_000
  CreditEAIUnlocksAccounts = 99_000
  ApplyUncreditedEAI = 99_000
  FixEAIUnlockBug = 99_000
  TargetPrice9999 = 99_000
